version: "3.4"
x-common-variables: &common-env-vars
  PORT_DB: ${PORT_DB:-3306}
  PORT_API: ${PORT_API:-8080}
  PORT_AUTH: ${PORT_AUTH:-8081}
  PORT_RABBITMQ: ${PORT_RABBITMQ:-5672}
  PORT_DISCOVERY: ${PORT_DISCOVERY:-8761}
  DISCOVERY_HOST: discovery
  GATEWAY_HOST: localhost
  AUTH_HOST: localhost
  RABBITMQ_HOST: rabbitmq
  JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "${PORT_RABBITMQ_DASHBOARD:-15672}:${PORT_RABBITMQ_DASHBOARD:-15672}"
    environment:
      RABBITMQ_DEFAULT_PASS: ${RABBIT_MQ_PASS:-guest}
      RABBITMQ_DEFAULT_USER: ${RABBIT_MQ_USER:-guest}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      timeout: 5s
      retries: 10
  discovery:
    build: services/discovery-service
    ports:
      - "${PORT_DISCOVERY:-8761}:${PORT_DISCOVERY:-8761}"
    healthcheck:
      test: [ "CMD", "curl" ,"-f", "discovery:${PORT_DISCOVERY:-8761}" ]
      timeout: 5s
      retries: 10
  gateway:
    depends_on:
      discovery:
        condition: service_healthy
    build: services/api-gateway
    ports:
      - "${PORT_API:-8080}:${PORT_API:-8080}"
    environment:
      <<: *common-env-vars
  mysql_activity:
    image: mysql
    environment:
      MYSQL_DATABASE: ${ACTIVITY_MYSQL_DATABASE:-activity_db}
      MYSQL_USER: ${ACTIVITY_MYSQL_USER:-activity_user}
      MYSQL_PASSWORD: ${ACTIVITY_MYSQL_PASSWORD:-activity_password}
      MYSQL_ROOT_PASSWORD: ${ACTIVITY_MYSQL_ROOT_PASSWORD:-root_password}
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10
  activity:
    depends_on:
      mysql_activity:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      discovery:
        condition: service_healthy
    build: services/activity-service
    environment:
      <<: *common-env-vars
      MYSQL_HOST: mysql_activity
      MYSQL_DATABASE: ${ACTIVITY_MYSQL_DATABASE:-activity_db}
      MYSQL_USER: ${ACTIVITY_MYSQL_USER:-activity_user}
      MYSQL_PASSWORD: ${ACTIVITY_MYSQL_PASSWORD:-activity_password}
      RABBITMQ_PASS: ${RABBIT_MQ_PASS:-guest}
      RABBITMQ_USER: ${RABBIT_MQ_USER:-guest}
  mysql_financial:
    image: mysql
    environment:
      MYSQL_DATABASE: ${FINANCIAL_MYSQL_DATABASE:-financial_db}
      MYSQL_USER: ${FINANCIAL_MYSQL_USER:-financial_user}
      MYSQL_PASSWORD: ${FINANCIAL_MYSQL_PASSWORD:-financial_password}
      MYSQL_ROOT_PASSWORD: ${FINANCIAL_MYSQL_ROOT_PASSWORD:-root_password}
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10
  financial:
    depends_on:
      mysql_financial:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      discovery:
        condition: service_healthy
    build: services/financial-service
    environment:
      <<: *common-env-vars
      MYSQL_HOST: mysql_financial
      MYSQL_DATABASE: ${FINANCIAL_MYSQL_DATABASE:-financial_db}
      MYSQL_USER: ${FINANCIAL_MYSQL_USER:-financial_user}
      MYSQL_PASSWORD: ${FINANCIAL_MYSQL_PASSWORD:-financial_password}
      RABBITMQ_PASS: ${RABBIT_MQ_PASS:-guest}
      RABBITMQ_USER: ${RABBIT_MQ_USER:-guest}
  google:
    depends_on:
      discovery:
        condition: service_healthy
    build: services/google-service
    environment:
      <<: *common-env-vars
  ui:
    depends_on:
      discovery:
        condition: service_healthy
    build: services/ui-service
    environment:
      <<: *common-env-vars
  mysql_authentication:
    image: mysql
    environment:
      MYSQL_DATABASE: ${AUTHENTICATION_MYSQL_DATABASE:-authentication_db}
      MYSQL_USER: ${AUTHENTICATION_MYSQL_USER:-authentication_user}
      MYSQL_PASSWORD: ${AUTHENTICATION_MYSQL_PASSWORD:-authentication_password}
      MYSQL_ROOT_PASSWORD: ${AUTHENTICATION_MYSQL_ROOT_PASSWORD:-root_password}
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10
  auth:
    depends_on:
      discovery:
        condition: service_healthy
      mysql_authentication:
        condition: service_healthy
    build: services/auth-service
    ports:
      - "${PORT_AUTH:-8081}:${PORT_AUTH:-8081}"
    environment:
      <<: *common-env-vars
      MYSQL_HOST: mysql_authentication
      MYSQL_DATABASE: ${AUTHENTICATION_MYSQL_DATABASE:-authentication_db}
      MYSQL_USER: ${AUTHENTICATION_MYSQL_USER:-authentication_user}
      MYSQL_PASSWORD: ${AUTHENTICATION_MYSQL_PASSWORD:-authentication_password}
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}